spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_mall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 87881092zz
  sql:
    init:
      mode: never

mybatis:
  type-aliases-package: com.demo.mymall.entity
  mapper-locations: classpath:mapper/*.xml